### PR TITLE
[HMR] fixed useable for styles with multiple refs

### PR DESCRIPTION
**Pull request by bloodyowl**
the issue was that the `!(refs++)` expression in `exports.ref`never hit `true` with HMR when you've got `refs` > 1.

this commit patches it without altering the behaviour in non-HMR conditions.

### CODE REVIEW

**Comment by MoOx** [comment]
Oh nice! This should fix style hot update in react components when you use/unuse styles in components update hooks.

**Comment by sokra** [comment]
Could you please check if this commit (5e5c3a0) also fixes the bug?

**Comment by bloodyowl** [comment]
seems that it does. thanks!
can you publish a npm release with that fix?

**Comment by sokra** [comment]
done

**Comment by MoOx** [comment]
:+1:

**Pull request closed without merging**
